let x = 2;
console.log(`x : ${x}`);
x += 2;
console.log(`x += 2 : ${x}`);
console.log('---');
console.log(`x : ${x}`);
x -= 2;
console.log(`x -= 2 : ${x}`);
console.log('---');
console.log(`x : ${x}`);
x *= 6;
console.log(`x *= 6 : ${x}`);
console.log('---');
console.log(`x : ${x}`);
x /= 3;
console.log(`x /= 3 : ${x}`);
console.log('---');
console.log(`x : ${x}`);
x **= 2;
console.log(`x **= 2 : ${x}`);
console.log('---');
console.log(`x : ${x}`);
x %= 3;
console.log(`x %= 3 : ${x}`);
console.log('---');
