// From zero to 10
let unities = [
  'zero',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
];

// From zero to 10
let twenties = [
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
  'sixteen',
  'seventeen',
  'eighteen',
  'nineteen',
];

// From zero to 10
let tens = [
  '',
  '',
  'twenty',
  'thirty',
  'fourty',
  'fifty',
  'sixty',
  'seventy',
  'eighty',
  'ninety',
];

// words for numbers
let units = [
  '',
  'thousand',
  'million',
  'billion',
  'trillion',
  'quadrillion',
  'quintillion',
  'sextillion',
  'septillion',
  'octillion',
  'nonillion',
  'decillion',
  'undecillion',
  'duodecillion',
  'tredecillion',
  'quattuordecillion',
  'quindecillion',
  'sexdecillion',
  'septendecillion',
  'octodecillion',
  'novemdecillion',
  'vigintillion',
  'unvigintillion',
  'duovigintillion',
  'trevigintillion',
  'quattuorvigintillion',
  'quinvigintillion',
  'sexvigintillion',
  'septenvigintillion',
  'octovigintillion',
  'novemvigintillion',
  'trigintillion',
  'untrigintillion',
  'duotrigintillion',
  'trestrigintillion',
  'quattuortrigintillion',
  'quintrigintillion',
  'sextrigintillion',
  'septentrigintillion',
  'octotrigintillion',
  'novemtrigintillion',
  'quadragintillion',
  'unquadragintillion',
  'duoquadragintillion',
  'trequadragintillion',
  'quattuorquadragintillion',
  'quinquadragintillion',
  'sexquadragintillion',
  'septenquadragintillion',
  'octoquadragintillion',
  'novemquadragintillion',
  'quinquagintillion',
  'unquinquagintillion',
  'duoquinquagintillion',
  'trequinquagintillion',
  'quattuorquinquagintillion',
  'quinquinquagintillion',
  'sexquinquagintillion',
  'septenquinquagintillion',
  'octoquinquagintillion',
  'novemquinquagintillion',
  'sexagintillion',
  'unsexagintillion',
  'duosexagintillion',
  'tresexagintillion',
  'quattuorsexagintillion',
  'quinsexagintillion',
];

export { unities, twenties, tens, units };
