let a = 4;
let b = 11;
let c = 21;
console.log('a : ', a);
console.log('b : ', b);
console.log('c : ', c);
a += b;
console.log('a += b : ', a);
a /= c;
console.log('a /= b : ', a);
c %= b;
console.log('c %= b : ', c);
console.log('a : ', a);
console.log('b : ', b);
console.log('c : ', c);
